#pragma once

// we define all the macros here

// #define NDN_DEBUG

#define NDN_NODE_LISTEN_TCP_PORT 8888
#define NDN_SERVER_ANNOUNCEMENT_INTERVAL_MS 500
#define NDN_ROUTER_ANNOUNCEMENT_RELAY_INTERVAL_MS 500
#define NDN_MAX_FILE_CHUNK 8192
#define NDN_DATA_DEFAULT_FRESHNESS_MS 3600000


#define NDN_USE_CACHE
// #define NDN_LOAD_BALANCE
// #define NDN_REPLICATE_REQUEST
